### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [jeanthom/boot2duino#4]
Hello!

I found this project from https://hackaday.com/2022/01/12/arduino-ide-creates-bootable-x86-floppy-disks/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by jeanthom** [comment]
Hi, thanks for reaching out. I decided to license this project under 0-clause BSD.

**Comment by vazhnov** [comment]
BSD license — great!
Thank you!
