### ISSUE TITLE
recipe.preproc.macros pattern is missing Arduino 1.8.19

### ISSUE THREAD

**Issue by TroyFletcher** [jeanthom/boot2duino#5]
`recipe.preproc.macros pattern is missing
Error compiling for board Generic x86 computer.`

Arduino would not recognize the new hardware folder until boards.txt was inside one of the subdirectories.

Building on windows 7, can test on a linux system later if necessary, I figure this was just a misplaced file.

**Comment by jeanthom** [comment]
Hi, I never got around to test boot2duino on Windows. Can you reproduce the issue on Linux?

**Comment by TroyFletcher** [comment]
Sorry for delay; compiling any example on Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux, running Arduino 1.8.13

```
/usr/bin/ld: warning: changing start of section .gnu.hash by 3 bytes
/usr/bin/ld: warning: changing start of section .plt by 11 bytes
/usr/bin/ld: warning: changing start of section .plt.got by 3 bytes
/usr/bin/ld: warning: changing start of section .rel.dyn by 3 bytes
/usr/bin/ld: warning: changing start of section .gnu.hash by 3 bytes
/usr/bin/ld: warning: changing start of section .plt by 11 bytes
/usr/bin/ld: warning: changing start of section .plt.got by 3 bytes
/usr/bin/ld: warning: changing start of section .rel.dyn by 3 bytes
/usr/bin/ld: section .dynamic LMA [0000000000007e00,0000000000007e8f] overlaps section .text LMA [0000000000007e00,0000000000007f54]
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Generic x86 computer.
```
GNU ld (GNU Binutils for Debian) 2.31.1

Strangely, this system doesn't complain about the location of boards.txt.

**Comment by jeanthom** [comment]
I assume you have GCC < 11, could you try updating to 11 or later? It seems to fix the issue (see https://github.com/jeanthom/boot2duino/issues/6)
