### ISSUE TITLE
Arduino IDE 1.8.19, "collect2 error: ld returned 1 exit status"

### ISSUE THREAD

**Issue by AndroidLeo01** [jeanthom/boot2duino#6]
Hi, guys, I wanted to try it but I'm not able to compile anything and I don't understand the problem. Here is the log message from the arduino IDE on my linux mint VM. I had to install g++, and i'm using version 9.3.0. Am i missing something? Need other information? To me, it seems a memory problem, but i set the VM with 8Gb RAM, and still have 12Gb of free space on HDD.
 
_/usr/bin/ld: warning: changing start of section .plt by 9 bytes
/usr/bin/ld: warning: changing start of section .plt.got by 1 byte
/usr/bin/ld: warning: changing start of section .gnu.version_d by 2 bytes
/usr/bin/ld: warning: changing start of section .gnu.version_r by 2 bytes
/usr/bin/ld: warning: changing start of section .dynsym by 2 bytes
/usr/bin/ld: warning: changing start of section .gnu.hash by 3 bytes
/usr/bin/ld: warning: changing start of section .plt by 9 bytes
/usr/bin/ld: warning: changing start of section .plt.got by 1 byte
/usr/bin/ld: warning: changing start of section .gnu.version_d by 2 bytes
/usr/bin/ld: warning: changing start of section .gnu.version_r by 2 bytes
/usr/bin/ld: warning: changing start of section .dynsym by 2 bytes
/usr/bin/ld: warning: changing start of section .gnu.hash by 3 bytes
/usr/bin/ld: section .dynamic LMA [0000000000007e00,0000000000007e8f] overlaps section .text LMA [0000000000007e00,0000000000007e26]
/usr/bin/ld: section .interp LMA [0000000000007e27,0000000000007e39] overlaps section .dynamic LMA [0000000000007e00,0000000000007e8f]
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Generic x86 computer._

Btw I love this project, what about LPT implementation? could transform an old PC into a freaking super IPC micro-controller lol

Thanks in advance

**Comment by AndroidLeo01** [comment]
[arduino_build_550520.tar.gz](https://github.com/jeanthom/boot2duino/files/7884323/arduino_build_550520.tar.gz)

Here is the tar file. Now i'm trying to install gcc-11

**Comment by AndroidLeo01** [comment]
YES Thank you! It was GCC version problem. I installed ubuntu 21 and gcc 11 and now it works perfectly! 
![immagine](https://user-images.githubusercontent.com/97912425/149993210-279defef-bbcf-4ad5-b798-d1abe49e2c8c.png)

**Comment by jeanthom** [comment]
Thanks for trying this! I'll write this in the README

**Comment by CyDefghi** [comment]
For the same issue, I just placed "*(.dynamic)" in the "/DISCARD/" section in the file "linker.ld". May be brutal, but it works with gcc 10.2.1 on Debian Bullseye.
