### ISSUE TITLE
working gcc update procedure

### ISSUE THREAD

**Issue by DavidJRichards** [jeanthom/boot2duino#7]
I used the procedure here to update gcc from v9 to v11 with the option to select either using update-alternatives and also installed the gui galternatives to help configure and select the default compiler.  

https://tutorialforlinux.com/2021/05/23/step-by-step-gcc-11-1-linux-mint-20-installation/

The demos build and run using Qemu in Linux Mint 20.3, I have not yet tried using a floppy on a real PC.

**Comment by jeanthom** [comment]
Thanks for reporting back, I'll include this in the README.
